######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 9 23:13:05 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
RESOURCES += animatedtiles.qrc
