######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 21 22:00:55 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mouse.h
SOURCES += main.cpp mouse.cpp
