######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 26 16:35:01 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += car.h carFrom.h carGenerator.h misc.h trafficLight.h
SOURCES += car.cpp carFrom.cpp carGenerator.cpp main.cpp trafficLight.cpp
