######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 2 13:56:39 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
