######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 9 10:10:57 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
