######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 9 15:38:33 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += example.cpp
