######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 9 23:22:11 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp
